//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cruid.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class players
    {
        public int playerID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public int countryID_player { get; set; }
        public int age { get; set; }
    
        public virtual country country { get; set; }
    }
}
