//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cruid.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public int PlayerID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public int CountryID_Player { get; set; }
        public int Age { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
