//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cruid
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public int countryID { get; set; }
        public string countryname { get; set; }
        public int playercount { get; set; }
    }
}
