//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cruid
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public int playerID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string country { get; set; }
        public int age { get; set; }
    
        public virtual player player1 { get; set; }
        public virtual player player2 { get; set; }
    }
}
